package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

// renderProjectMkdocsYml writes the per-project mkdocs.yml that inherits the
// selected template's base configuration and sets the generated project paths.
// This makes each project a standalone buildable site.
//
// All paths in the emitted config are RELATIVE TO THE LOCATION of the
// per-project mkdocs.yml (docs/api/<slug>/mkdocs.yml), because MkDocs resolves
// them that way. From docs/api/<slug>/ the repo layout is:
//
//	content/                   -> this project's Markdown and public assets
//	../../api-published/<slug> -> this project's rendered site
//	mkdocs.base.yml             -> copied from the selected template
func renderProjectMkdocsYml(p *Project, projectOutDir string, sourceDir string) error {
	assetVersion, err := siteContentVersion(sourceDir)
	if err != nil {
		return fmt.Errorf("compute site content version: %w", err)
	}
	cfg := fmt.Sprintf(`# Generated by xojo-docgen. Each project is a standalone MkDocs site.
# Build with: mkdocs build -f %s

site_name: %s — API
docs_dir: content
site_dir: ../../api-published/%s
extra:
  asset_version: %s

# Inherit the selected template configuration copied into this project.
INHERIT: mkdocs.base.yml

# Per-project site URL. Leave commented for root hosting; uncomment and set for
# subpath hosting (e.g. GitHub Pages project sites).
# site_url: https://<user>.github.io/<repo>/%s/

use_directory_urls: true
`,
		filepath.ToSlash(filepath.Join(projectOutDir, "mkdocs.yml")),
		p.Name,
		p.Slug,
		assetVersion,
		p.Slug,
	)
	return os.WriteFile(filepath.Join(projectOutDir, "mkdocs.yml"), []byte(cfg), 0o644)
}

func siteContentVersion(sourceDir string) (string, error) {
	var files []string
	err := filepath.WalkDir(sourceDir, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.Type().IsRegular() {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		return "", err
	}
	sort.Strings(files)

	digest := sha256.New()
	for _, path := range files {
		relative, err := filepath.Rel(sourceDir, path)
		if err != nil {
			return "", err
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return "", err
		}
		digest.Write([]byte(filepath.ToSlash(relative)))
		digest.Write([]byte{0})
		digest.Write(content)
		digest.Write([]byte{0})
	}
	return hex.EncodeToString(digest.Sum(nil))[:16], nil
}

// renderNoJekyll writes an empty .nojekyll into the published dir so GitHub
// Pages doesn't strip _-prefixed assets.
func renderNoJekyll(publishedDir string) error {
	if err := os.MkdirAll(publishedDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(publishedDir, ".nojekyll"), []byte{}, 0o644)
}
