package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// renderProjectMkdocsYml writes the per-project mkdocs.yml that inherits the
// selected template's base configuration and sets the generated project paths.
// This makes each project a standalone buildable site.
//
// All paths in the emitted config are RELATIVE TO THE LOCATION of the
// per-project mkdocs.yml (docs/api/<slug>/mkdocs.yml), because MkDocs resolves
// them that way. From docs/api/<slug>/ the repo layout is:
//
//	.                          -> this project's Markdown source
//	../../api-published/<slug> -> this project's rendered site
//	mkdocs.base.yml             -> copied from the selected template
func renderProjectMkdocsYml(p *Project, projectOutDir string) error {
	cfg := fmt.Sprintf(`# Generated by xojo-docgen. Each project is a standalone MkDocs site.
# Build with: mkdocs build -f %s

site_name: %s — API
docs_dir: .
site_dir: ../../api-published/%s

# Inherit the selected template configuration copied into this project.
INHERIT: mkdocs.base.yml

# Per-project site URL. Leave commented for root hosting; uncomment and set for
# subpath hosting (e.g. GitHub Pages project sites).
# site_url: https://<user>.github.io/<repo>/%s/

use_directory_urls: true
`,
		filepath.ToSlash(filepath.Join(projectOutDir, "mkdocs.yml")),
		p.Name,
		p.Slug,
		p.Slug,
	)
	return os.WriteFile(filepath.Join(projectOutDir, "mkdocs.yml"), []byte(cfg), 0o644)
}

// renderNoJekyll writes an empty .nojekyll into the published dir so GitHub
// Pages doesn't strip _-prefixed assets.
func renderNoJekyll(publishedDir string) error {
	if err := os.MkdirAll(publishedDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(publishedDir, ".nojekyll"), []byte{}, 0o644)
}

// suppressUnused avoids a compile error if a helper is not used.
var _ = strings.TrimSpace
