package main

import (
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const defaultPrimaryColor = "11,99,56"

// RGBColor is an sRGB color with 8-bit channels.
type RGBColor struct {
	R int
	G int
	B int
}

func parsePrimaryColor(value string) (RGBColor, error) {
	parts := strings.Split(value, ",")
	if len(parts) != 3 {
		return RGBColor{}, fmt.Errorf("expected R,G,B (for example %s)", defaultPrimaryColor)
	}

	channels := make([]int, 3)
	for index, part := range parts {
		channel, err := strconv.Atoi(strings.TrimSpace(part))
		if err != nil || channel < 0 || channel > 255 {
			return RGBColor{}, fmt.Errorf("RGB channels must be integers from 0 to 255: %q", value)
		}
		channels[index] = channel
	}
	return RGBColor{R: channels[0], G: channels[1], B: channels[2]}, nil
}

func (color RGBColor) hex() string {
	return fmt.Sprintf("#%02X%02X%02X", color.R, color.G, color.B)
}

func (color RGBColor) cssRGB() string {
	return fmt.Sprintf("%d, %d, %d", color.R, color.G, color.B)
}

func (color RGBColor) mix(other RGBColor, amount float64) RGBColor {
	if amount < 0 {
		amount = 0
	}
	if amount > 1 {
		amount = 1
	}
	return RGBColor{
		R: int(math.Round(float64(color.R)*(1-amount) + float64(other.R)*amount)),
		G: int(math.Round(float64(color.G)*(1-amount) + float64(other.G)*amount)),
		B: int(math.Round(float64(color.B)*(1-amount) + float64(other.B)*amount)),
	}
}

func (color RGBColor) relativeLuminance() float64 {
	channel := func(value int) float64 {
		srgb := float64(value) / 255
		if srgb <= 0.04045 {
			return srgb / 12.92
		}
		return math.Pow((srgb+0.055)/1.055, 2.4)
	}
	return 0.2126*channel(color.R) + 0.7152*channel(color.G) + 0.0722*channel(color.B)
}

func contrastRatio(first RGBColor, second RGBColor) float64 {
	firstLuminance := first.relativeLuminance()
	secondLuminance := second.relativeLuminance()
	if firstLuminance < secondLuminance {
		firstLuminance, secondLuminance = secondLuminance, firstLuminance
	}
	return (firstLuminance + 0.05) / (secondLuminance + 0.05)
}

func accessibleVariant(primary RGBColor, background RGBColor, toward RGBColor) RGBColor {
	if contrastRatio(primary, background) >= 4.5 {
		return primary
	}
	for step := 1; step <= 20; step++ {
		candidate := primary.mix(toward, float64(step)*0.05)
		if contrastRatio(candidate, background) >= 4.5 {
			return candidate
		}
	}
	return toward
}

func contrastText(background RGBColor) RGBColor {
	white := RGBColor{R: 255, G: 255, B: 255}
	black := RGBColor{}
	if contrastRatio(background, white) >= contrastRatio(background, black) {
		return white
	}
	return black
}

func renderPrimaryColorCSS(primary RGBColor) string {
	white := RGBColor{R: 255, G: 255, B: 255}
	black := RGBColor{}
	lightBackground := white
	darkBackground := RGBColor{R: 16, G: 21, B: 18}

	light := primary.mix(white, 0.24)
	dark := primary.mix(black, 0.30)
	soft := primary.mix(white, 0.80)
	lightAccent := accessibleVariant(primary, lightBackground, black)
	darkAccent := accessibleVariant(primary, darkBackground, white)
	darkSoft := primary.mix(darkBackground, 0.64)

	return fmt.Sprintf(`/* Generated by xojo-docgen from primary RGB %d,%d,%d.
   Regenerate this file with -primary-color; do not edit generated output. */
:root {
  --xojo-primary: %s;
  --xojo-primary-rgb: %s;
  --xojo-primary-light: %s;
  --xojo-primary-dark: %s;
  --xojo-primary-soft: %s;
  --xojo-primary-on: %s;
  --xojo-primary-accent: %s;
  --xojo-primary-border: rgba(%s, 0.40);
  --xojo-primary-rule: rgba(%s, 0.20);
  --xojo-primary-wash: rgba(%s, 0.10);
}

:root[data-theme="dark"] {
  --xojo-primary: %s;
  --xojo-primary-rgb: %s;
  --xojo-primary-light: %s;
  --xojo-primary-dark: %s;
  --xojo-primary-soft: %s;
  --xojo-primary-on: %s;
  --xojo-primary-accent: %s;
  --xojo-primary-border: rgba(%s, 0.46);
  --xojo-primary-rule: rgba(%s, 0.24);
  --xojo-primary-wash: rgba(%s, 0.14);
}
`,
		primary.R, primary.G, primary.B,
		primary.hex(), primary.cssRGB(), light.hex(), dark.hex(), soft.hex(),
		contrastText(primary).hex(), lightAccent.hex(),
		primary.cssRGB(), primary.cssRGB(), primary.cssRGB(),
		darkAccent.hex(), darkAccent.cssRGB(), darkAccent.mix(white, 0.22).hex(), darkAccent.mix(black, 0.28).hex(),
		darkSoft.hex(), contrastText(darkAccent).hex(), darkAccent.hex(),
		darkAccent.cssRGB(), darkAccent.cssRGB(), darkAccent.cssRGB(),
	)
}

func writePrimaryColorCSS(outDir string, primary RGBColor) error {
	path := filepath.Join(outDir, "stylesheets", "primary-color.css")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(renderPrimaryColorCSS(primary)), 0o644)
}
